### ISSUE TITLE
Search not working in production

### ISSUE THREAD

**Issue by dadofsambonzuki** [HolgerHatGarKeineNode/geojson-helper#11]
Hey man,

Looks like search in prod has stopped working. Could you take a look when you get a second please?

Cheers,

Nathan

**Comment by HolgerHatGarKeineNode** [comment]
Thank you for your message. I'll have a look at why empty replies are coming back. Maybe something has been changed in the APIs. Will have to look at it in the meantime though as Christmas preparations are already in full swing. 🎄

**Comment by HolgerHatGarKeineNode** [comment]
Fixed.

There was a API rate limiting on https://nominatim.openstreetmap.org

I've registered a new email and let's see if we will hit the rate limit again.

**Comment by dadofsambonzuki** [comment]
Excellent, thanks.
